#!/bin/bash
THREADS=$(cat path.o$1 |  grep 't:' | tr -d ' ' | cut -d ':' -f 2)
RUNTIME=$(cat path.o$1 |  grep 'Time:' | tr -d ' ' | cut -d ':' -f 2)
# RUNTIME=$(cat path.o$1 | grep 'Time:' | cut -d ' ' -f 1)
echo $THREADS,$RUNTIME >> $2
