#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -N path
#PBS -j oe
set OMP_NM_THREADS = 4
module load cs5220
cd $PBS_O_WORKDIR
mpirun -np 1  ./floyd-warshall -n 1024
mpirun -np 2  ./floyd-warshall -n 1024
mpirun -np 4  ./floyd-warshall -n 1024
mpirun -np 8  ./floyd-warshall -n 1024
mpirun -np 16 ./floyd-warshall -n 1024
mpirun -np 24 ./floyd-warshall -n 1024
