#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -n
#PBS -p 1023
#PBS -j oe

set -eou pipefail

main() {
    if [ -z ${EXE+x} ] || [ -z ${N+x} ]; then
        echo "usage: qsub run.pbs -N <name> -vEXE=<executable>,N=<n>[,AMPL=]"
        exit -1
    fi

    if [ -z ${AMPL+x} ]; then
        "$EXE" -n "$N"
    else
        amplxe-cl -collect hotspots -r "$EXE-ampl" \
        "$EXE" -n "$N"
    fi
}

module load cs5220
cd $PBS_O_WORKDIR
main
