#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -N path-blocked
#PBS -j oe

module load cs5220
cd $PBS_O_WORKDIR
export OMP_CANCELLATION=true
export OMP_NUM_THREADS=24
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
./path-blocked.x -n 2000
