#!/bin/sh -l
# The default values forp_prob is 0.05.
# To run this: qsub -v prob=probability path-mpi_weak-.pbs

p_prob=${prob:-0.05}

rm weak_mpi_${p_prob}*

n_nodes=(1000 1414 2000 2449 2828 3464 4243 4899)
cont=0

for n_process in 1 2 4 6 8 12 18 24
do

	module load cs5220
	cd $PBS_O_WORKDIR

	#PBS -l nodes=1:ppn=24
	#PBS -l walltime=0:30:00
	#PBS -N path
	#PBS -j oe

	mpirun -n ${n_process} ./path-mpi.x -n ${n_nodes[cont]} >> weak_mpi_${p_prob}.txt
	
	let cont=$cont+1
done
