#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -N path-mpi_strong
#PBS -j oe

module load cs5220
cd $PBS_O_WORKDIR
# mpirun -np 4 ./path-mpi.x -n 64 -i adj_mat -o out_mat
mpirun -np 1 ./path-mpi.x -n 1000
mpirun -np 2 ./path-mpi.x -n 1000
mpirun -np 4 ./path-mpi.x -n 1000
mpirun -np 5 ./path-mpi.x -n 1000
mpirun -np 8 ./path-mpi.x -n 1000
mpirun -np 10 ./path-mpi.x -n 1000
mpirun -np 20 ./path-mpi.x -n 1000
